Update description of mkosi
OSMakers/image-build-tools pull request #3
Opened 2024-03-08 19:04 UTC by keszybz

2024-03-09 09:01 UTC, DaanDeMeyer commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
The 3-8 minutes is rather arbitrary since image build time is a function of how many and which packages you install mostly. (And your network connection speed if they're not cached already)

2024-03-09 11:05 UTC, behrmann reviewed
Thanks for the work, @keszybz :) 

Something for the overview block could be a "target audience" or rather "who has adopted this tool so far". mkosi's raison d'être was testing systemd, but thanks to @DaanDeMeyer's work more people are picking it up for their upstream work, e.g. some kernel devs. The other people we get a lot in our issues and on Matrix are the confidential computing people, people building appliances and people trying to make immutable OSs based on existing distros.

2024-03-09 11:05 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
> +-  Supported host distributions: Fedora, CentOS/RHEL, (open)SUSE, Debian/Ubuntu, Arch
Nix and Gentoo (probably) also work. Generally anything that supports the package manager of the target distribution should work.

2024-03-09 11:05 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
```suggestion
competitors (around 3-8 minutes) and caching of downloaded packages and package manager metadata as well as incremental builds and overlays can be used to reduce image build times. 
```

2024-03-09 11:05 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
>  -  Site: https://github.com/systemd/mkosi
Since we have a nice site now
```suggestion
-  Site: https://mkosi.systemd.io, https://github.com/systemd/mkosi
```
or since it also links the github page just the former.

2024-03-09 11:05 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
I'd also add 
> Images can be built by unprivileged users.

I'm sure others can do this as well (KIWI via VMs if I recall correctly), but some of the tools on the list are new to me and I don't know which ones do support it.

2024-03-09 11:05 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
> +direct kernel boots are supported. Images are built from scratch, but
Slight style nit: "allowed" sounds a stilted, but I see saying "supported" would clash with it being used in the next clause. How about something along the lines
```suggestion
Currently UEFI and BIOS images using sd-boot (only for UEFI) and grub, as well as
direct kernel boots for Qemu are supported. SecureBoot is supported both using self-enrolled certificates and shim. Images are built from scratch, but
```

2024-03-09 12:01 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
>  -  Site: https://github.com/systemd/mkosi
Good point.

2024-03-09 12:02 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
Yeah, but this is about giving a ballpark estimate. E.g 5-10 minutes is quite different than 30-40.

2024-03-09 12:04 UTC, keszybz commented
Updated with all the suggestions.

2024-03-09 12:07 UTC, behrmann approved these changes

2024-03-09 12:07 UTC, behrmann commented on Linux-Image-Creation-Tools.rst
> +-  Supported host distributions: Fedora, CentOS/RHEL, (open)SUSE, Debian/Ubuntu, Arch, Gentoo, Nix
I was a bit short there, I think they call themselves "NixOS" properly, with Nix just being the package manager.

2024-03-09 12:10 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +-  Supported host distributions: Fedora, CentOS/RHEL, (open)SUSE, Debian/Ubuntu, Arch, Gentoo, Nix
Updated again.

2024-03-09 12:12 UTC, DaanDeMeyer commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
Right but then we should maybe lower the estimates a bit. Generating a bootable arch disk image using mkosi's default configuration (230 packages which is relatively beefy for Arch) takes 1min and 50s on my laptop with most packages cached.

A minimal bootable fedora disk image with just a kernel, systemd and udev takes 30s. 

So the ballpark estimate should be adjusted to something like 1-5min I think.

2024-03-09 12:18 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
OK, I reworded the text again. PTAL.

2024-03-09 12:21 UTC, daandemeyer requested changes

2024-03-09 12:21 UTC, daandemeyer commented on Linux-Image-Creation-Tools.rst
> +of downloaded packages and package manager metadata, image image
double image

2024-03-09 12:21 UTC, daandemeyer commented on Linux-Image-Creation-Tools.rst
> +users.
I would say, "Images can be built without needing root privileges" and "Disk images can be built from (system) containers without needing loop devices using systemd-repart".

2024-03-09 12:34 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +users.
"unprivileged" and "without needing root privileges" are the same thing. I reworded the description again, PTAL.

2024-03-09 13:47 UTC, DaanDeMeyer approved these changes

2024-03-09 13:47 UTC, DaanDeMeyer commented on Linux-Image-Creation-Tools.rst
> +image build times. Images can be built by entirely unprivileged users
Maybe we should mention for completeness that we do rely on newuidmap and newgidmap being properly configured for those users in /etc/subuid and /etc/subgid

2024-03-09 14:34 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +image build times. Images can be built by entirely unprivileged users
I think we're getting into too much detail. But I'll drop "entirely" from the sentence, it gives the wrong impression.

2024-03-09 17:58 UTC, Conan-Kudo requested changes

2024-03-09 17:58 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +-  Site: http://mkosi.systemd.io, https://github.com/systemd/mkosi
If there's a real website, drop the GitHub repo URL.

2024-03-09 17:58 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +Currently UEFI and BIOS images using sd-boot (only for UEFI) and grub,
This sentence is awkwardly constructed.

2024-03-11 08:32 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +Currently UEFI and BIOS images using sd-boot (only for UEFI) and grub,
Reworded.

2024-03-11 08:34 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +-  Site: http://mkosi.systemd.io, https://github.com/systemd/mkosi
I think both are useful. Sometimes you're looking for the git repo, and then all the docs are just a distraction, and at other times you're looking for the docs, and don't care about the raw repo content. The website has a link to the repo, somewhere, but it requires a bit of searching to find.

2024-03-11 11:09 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +-  Site: http://mkosi.systemd.io, https://github.com/systemd/mkosi
That sounds like a problem with the website then. I would like a sole website listed. When I wrote this document originally (several years ago), it did not have a website.

2024-03-11 11:10 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
Please do not assume caching with estimates.

2024-03-11 11:31 UTC, daandemeyer commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
@Conan-Kudo Estimates without assuming packages are already downloaded are going to be extremely inaccurate since the biggest part will be downloading packages which depends a lot on the user's network connection.

2024-03-11 12:16 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
I had to do that because some of the tools on this list do not support caching at all (notably lorax and osbuild).

2024-03-11 12:18 UTC, Conan-Kudo commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
All the estimates were originally done with a local mirror, so the download step does not include variable internet access.

2024-03-11 19:49 UTC, keszybz commented on Linux-Image-Creation-Tools.rst
> +competitors (around 3-8 minutes) at the cost of some flexibility.
Yeah, if caching works, then specifying the time with the cache populated is the most useful. Then anyone can add the time required to download the packages to this baseline. But the time to downloads depends very much on the local connection bandwidth and on the number of packages, but is fairly predictable. When doing development, you generally have do similar package sets over and over, so caching is very effective.

2024-03-13 11:32 UTC, keszybz commented
OK, can we get this merged? It's a one-para update that is not worth spending too much time on. I think we're currently very much in bike-shedding territory.

2024-03-13 11:41 UTC, Conan-Kudo approved these changes
I'll make further updates afterward then.

2024-03-13 11:42 UTC, merged